package tests;

import controllers.SimpleController;
import java.io.File;
import java.io.IOException;

import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

import com.formdev.flatlaf.FlatLightLaf;

import pseudofiles.PseudoFile;

public class TestView extends javax.swing.JFrame {

    SimpleController mySimpleController;

    public TestView() {
        initComponents();

        PseudoFile pseudoFile = new PseudoFile(
            new File("data/testFile.csv"), 
            new String[] { "Cedula", "Nombre", "Edad" }
        );

        mySimpleController = new SimpleController(
            (DefaultTableModel) test_table.getModel(), 
            pseudoFile
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        test_table = new javax.swing.JTable();
        update_button = new javax.swing.JButton();
        rewrite_button = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 100, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 100, Short.MAX_VALUE));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        test_table.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

        }, new String[] { "Cedula", "Nombre", "Edad" }) {
            Class[] types = new Class[] { java.lang.String.class, java.lang.String.class, java.lang.String.class };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        jScrollPane1.setViewportView(test_table);

        update_button.setText("updateTable");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        rewrite_button.setText("rewriteFile");
        rewrite_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rewrite_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addGap(75, 75, 75)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(86, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup().addGap(142, 142, 142).addComponent(update_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rewrite_button).addGap(152, 152, 152)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(update_button).addComponent(rewrite_button))
                        .addGap(33, 33, 33)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_update_buttonActionPerformed
        try {
            mySimpleController.updateTable();
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }// GEN-LAST:event_update_buttonActionPerformed

    private void rewrite_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rewrite_buttonActionPerformed
        try {
            mySimpleController.reWriteFile();
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }// GEN-LAST:event_rewrite_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        /*
         * try { for (javax.swing.UIManager.LookAndFeelInfo info :
         * javax.swing.UIManager.getInstalledLookAndFeels()) { if
         * ("Nimbus".equals(info.getName())) {
         * javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; } } } catch
         * (ClassNotFoundException ex) {
         * java.util.logging.Logger.getLogger(TestView.class.getName()).log(java.util.
         * logging.Level.SEVERE, null, ex); } catch (InstantiationException ex) {
         * java.util.logging.Logger.getLogger(TestView.class.getName()).log(java.util.
         * logging.Level.SEVERE, null, ex); } catch (IllegalAccessException ex) {
         * java.util.logging.Logger.getLogger(TestView.class.getName()).log(java.util.
         * logging.Level.SEVERE, null, ex); } catch
         * (javax.swing.UnsupportedLookAndFeelException ex) {
         * java.util.logging.Logger.getLogger(TestView.class.getName()).log(java.util.
         * logging.Level.SEVERE, null, ex); }
         */

        try {
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException e) {
            System.out.println("no se puedo chicos");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rewrite_button;
    private javax.swing.JTable test_table;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}
