
package views.clientviews.formviews;

import logic.FieldMapper;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

import forms.Form;
import forms.PseudoWriterForm;
import forms.registerforms.RegisterAppointment;
import java.awt.event.ActionEvent;
import models.AppointmentType;
import pseudofiles.PseudoFile;
import views.vetviews.VetReviewView;
import logic.AppointmentHandler;
import logic.AssociativeCombo;
import logic.AssociativeForeignCombo;
import models.Veterinarian;
import models.Appointment;
import models.Pet;


public class AppoimentViewForm extends javax.swing.JDialog {
    
    private PseudoFile saveAppoFile; 
    private FieldMapper vetCombo;
    private FieldMapper appoTypeCombo;
    private FieldMapper petCombo;
    
    public AppoimentViewForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        centreWindow();
 
        PseudoFile vetFile = new PseudoFile(
            new File("data/veterinarios.csv"), 
            Veterinarian.getColumns()
        );
        PseudoFile appoTypeFile = new PseudoFile(
            new File("data/tipo_citas.csv"), 
            AppointmentType.getColumns()
        );

        vetCombo = new AssociativeCombo(vetFile, "cedula", "nombre");
        appoTypeCombo = new AssociativeCombo(appoTypeFile, "tipo", "nombre");
        
        vet_combo.setModel(vetCombo.getComboModel());
        appo_type_combo.setModel(appoTypeCombo.getComboModel());
        
        vet_combo.addActionListener ((ActionEvent e) -> {
            setDateModel();
        });
        
        setDateModel();
 
    }

    public void setSaveAppoFile(PseudoFile saveAppoFile) {
        this.saveAppoFile = saveAppoFile;
    }

    private void setDateModel(){
        PseudoFile appoFile = new PseudoFile(
            new File("data/citas.csv"), 
            Appointment.getColumns()
        );
        PseudoFile pendingAppoFile = new PseudoFile(
            new File("data/citas_pendientes.csv"), 
            Appointment.getColumns()
        );
        AppointmentHandler apoHandler = new AppointmentHandler();
        apoHandler.generateDates();
        apoHandler.filterDates(pendingAppoFile, (String)vet_combo.getSelectedItem());
        apoHandler.filterDates(appoFile, (String)vet_combo.getSelectedItem());
        date_combo.setModel(apoHandler.getComboModel());
    }
    
    public void setPetModels(String clientCed){
        PseudoFile petFile = new PseudoFile(
            new File("data/mascotas.csv"), 
            Pet.getColumns()
        );
        petCombo = new AssociativeForeignCombo(petFile, "petId", "nombre", 
            "clientCed", clientCed
        );
        pet_combo.setModel(petCombo.getComboModel());
    }
    
    private void centreWindow() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y - 25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        header_title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        register_client_button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        adress_label = new javax.swing.JLabel();
        pet_combo = new javax.swing.JComboBox<>();
        adress_label1 = new javax.swing.JLabel();
        appo_type_combo = new javax.swing.JComboBox<>();
        adress_label2 = new javax.swing.JLabel();
        vet_combo = new javax.swing.JComboBox<>();
        adress_label3 = new javax.swing.JLabel();
        date_combo = new javax.swing.JComboBox<>();
        register_client_button1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        header.setBackground(new java.awt.Color(45, 106, 79));
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.setAlignmentY(0.0F);
        header.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 15));

        header_title.setBackground(new java.awt.Color(55, 71, 79));
        header_title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        header_title.setForeground(new java.awt.Color(255, 255, 255));
        header_title.setText("Agendar Cita");
        header.add(header_title);

        jPanel1.setBackground(new java.awt.Color(249, 247, 247));

        jPanel2.setBackground(new java.awt.Color(247, 249, 249));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 40, 30));

        register_client_button.setBackground(new java.awt.Color(64, 145, 108));
        register_client_button.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        register_client_button.setForeground(new java.awt.Color(255, 255, 255));
        register_client_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-login-24.png"))); // NOI18N
        register_client_button.setText("Agendar");
        register_client_button.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 25, 10, 25));
        register_client_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_client_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAccpetForm(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(247, 249, 249));
        jPanel3.setLayout(new java.awt.GridLayout(4, 2, 0, 20));

        adress_label.setBackground(new java.awt.Color(247, 249, 249));
        adress_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adress_label.setForeground(new java.awt.Color(33, 33, 33));
        adress_label.setText("Mascota:");
        jPanel3.add(adress_label);

        pet_combo.setBackground(new java.awt.Color(255, 255, 255));
        pet_combo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pet_combo.setForeground(new java.awt.Color(33, 33, 33));
        pet_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ninguna" }));
        pet_combo.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 0));
        pet_combo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pet_combo.setPreferredSize(new java.awt.Dimension(200, 27));
        jPanel3.add(pet_combo);

        adress_label1.setBackground(new java.awt.Color(247, 249, 249));
        adress_label1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adress_label1.setForeground(new java.awt.Color(33, 33, 33));
        adress_label1.setText("Tipo de Cita:");
        jPanel3.add(adress_label1);

        appo_type_combo.setBackground(new java.awt.Color(255, 255, 255));
        appo_type_combo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        appo_type_combo.setForeground(new java.awt.Color(33, 33, 33));
        appo_type_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ninguna" }));
        appo_type_combo.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 0));
        appo_type_combo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        appo_type_combo.setPreferredSize(new java.awt.Dimension(200, 27));
        jPanel3.add(appo_type_combo);

        adress_label2.setBackground(new java.awt.Color(247, 249, 249));
        adress_label2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adress_label2.setForeground(new java.awt.Color(33, 33, 33));
        adress_label2.setText("Veterinario");
        jPanel3.add(adress_label2);

        vet_combo.setBackground(new java.awt.Color(255, 255, 255));
        vet_combo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vet_combo.setForeground(new java.awt.Color(33, 33, 33));
        vet_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ninguna" }));
        vet_combo.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 0));
        vet_combo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        vet_combo.setPreferredSize(new java.awt.Dimension(200, 27));
        jPanel3.add(vet_combo);

        adress_label3.setBackground(new java.awt.Color(247, 249, 249));
        adress_label3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adress_label3.setForeground(new java.awt.Color(33, 33, 33));
        adress_label3.setText("Fecha:");
        jPanel3.add(adress_label3);

        date_combo.setBackground(new java.awt.Color(255, 255, 255));
        date_combo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        date_combo.setForeground(new java.awt.Color(33, 33, 33));
        date_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ninguna" }));
        date_combo.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 0));
        date_combo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        date_combo.setPreferredSize(new java.awt.Dimension(200, 27));
        jPanel3.add(date_combo);

        register_client_button1.setBackground(new java.awt.Color(64, 145, 108));
        register_client_button1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        register_client_button1.setForeground(new java.awt.Color(255, 255, 255));
        register_client_button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-login-24.png"))); // NOI18N
        register_client_button1.setText("Ver Vet Reviews");
        register_client_button1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 25, 10, 25));
        register_client_button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_client_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onVetReviwes(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(398, 398, 398)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(register_client_button1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(register_client_button)
                        .addGap(31, 31, 31)))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(register_client_button)
                        .addGap(18, 18, 18)
                        .addComponent(register_client_button1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onAccpetForm(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAccpetForm
        Form registerForm = new RegisterAppointment(
                (String)date_combo.getSelectedItem(),
                (String)appoTypeCombo.getRealValue(),
                (String)petCombo.getRealValue(),
                (String)vetCombo.getRealValue()
        );
        PseudoWriterForm pseudoWriterForm = new PseudoWriterForm(
            registerForm, 
            saveAppoFile
        );
        pseudoWriterForm.writeRegister();
        setDateModel();
    }//GEN-LAST:event_onAccpetForm

    private void onVetReviwes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onVetReviwes
        VetReviewView dialogForm = new VetReviewView(
            (JFrame) SwingUtilities.getWindowAncestor(this), true
        );
        dialogForm.setCedVet(vetCombo.getRealValue());
        dialogForm.setVisible(true);
    }//GEN-LAST:event_onVetReviwes

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppoimentViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppoimentViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppoimentViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppoimentViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AppoimentViewForm dialog = new AppoimentViewForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adress_label;
    private javax.swing.JLabel adress_label1;
    private javax.swing.JLabel adress_label2;
    private javax.swing.JLabel adress_label3;
    private javax.swing.JComboBox<String> appo_type_combo;
    private javax.swing.JComboBox<String> date_combo;
    private javax.swing.JPanel header;
    private javax.swing.JLabel header_title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> pet_combo;
    private javax.swing.JButton register_client_button;
    private javax.swing.JButton register_client_button1;
    private javax.swing.JComboBox<String> vet_combo;
    // End of variables declaration//GEN-END:variables
}
