package views.adminviews;

import java.io.File;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import models.Appointment;
import pseudofiles.PseudoFile;
import views.clientviews.formviews.AppoimentViewForm;
import forms.registerforms.Validation;
import inevaup.dialogs.InfoDialog;

public class AdminAppoCreateView extends javax.swing.JPanel {

    
    public AdminAppoCreateView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        card_content_layout = new javax.swing.JPanel();
        modify_button = new javax.swing.JButton();
        ced_field = new javax.swing.JTextField();
        ced_label = new javax.swing.JLabel();

        card_content_layout.setBackground(new java.awt.Color(247, 249, 249));

        modify_button.setBackground(new java.awt.Color(64, 145, 108));
        modify_button.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        modify_button.setForeground(new java.awt.Color(255, 255, 255));
        modify_button.setText("Ir al formulario");
        modify_button.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 25, 10, 25));
        modify_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modify_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnMoveToForm(evt);
            }
        });

        ced_field.setBackground(new java.awt.Color(255, 255, 255));
        ced_field.setColumns(15);
        ced_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ced_field.setForeground(new java.awt.Color(33, 33, 33));
        ced_field.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ced_field.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 189, 189)), javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7)));
        ced_field.setMargin(new java.awt.Insets(10, 10, 10, 10));
        ced_field.setName(""); // NOI18N

        ced_label.setBackground(new java.awt.Color(247, 249, 249));
        ced_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ced_label.setForeground(new java.awt.Color(33, 33, 33));
        ced_label.setText("Cedula");

        javax.swing.GroupLayout card_content_layoutLayout = new javax.swing.GroupLayout(card_content_layout);
        card_content_layout.setLayout(card_content_layoutLayout);
        card_content_layoutLayout.setHorizontalGroup(
            card_content_layoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card_content_layoutLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(ced_label, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ced_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(modify_button)
                .addGap(145, 145, 145))
        );
        card_content_layoutLayout.setVerticalGroup(
            card_content_layoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card_content_layoutLayout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addGroup(card_content_layoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ced_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modify_button)
                    .addComponent(ced_label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(237, 237, 237))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(card_content_layout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(card_content_layout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void OnMoveToForm(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnMoveToForm
        PseudoFile appoFile = new PseudoFile(
            new File("data/citas_pendientes.csv"), 
            Appointment.getColumns()
        );
        Validation v = new Validation();
        if(v.validateCharField(ced_field.getText(), 1, 20)){
        
            AppoimentViewForm appoView = new AppoimentViewForm(
                (JFrame) SwingUtilities.getWindowAncestor(this), true
            );
            appoView.setSaveAppoFile(appoFile);
            appoView.setPetModels(ced_field.getText());
            appoView.setVisible(true);
        }else{
            invalidFormDialog();
        }
    }//GEN-LAST:event_OnMoveToForm

    
    private void invalidFormDialog(){
        InfoDialog dialog = new InfoDialog(null, "Error en el formulario", 
            "Cedula invalida", InfoDialog.TypeInfoDialog.ERROR_DIALOG
        );
        dialog.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel card_content_layout;
    private javax.swing.JTextField ced_field;
    private javax.swing.JLabel ced_label;
    private javax.swing.JButton modify_button;
    // End of variables declaration//GEN-END:variables
}
