package views.adminviews;

import controllers.BaseController;
import controllers.SimpleController;
import inevaup.dialogs.InfoDialog;
import inevaup.dialogs.WarningDialog;
import java.io.File;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import models.AppointmentType;
import pseudofiles.PseudoFile;
import views.adminviews.formviews.AppoTypeViewForm;


public class AppoTypeView extends javax.swing.JPanel {
    
    private final BaseController controller;
    
    public AppoTypeView() {
        initComponents();
        
        PseudoFile pseudoFile = new PseudoFile(
            new File("data/tipo_citas.csv"), 
            AppointmentType.getColumns()
        );

        controller = new SimpleController(
            (DefaultTableModel) appo_type_table.getModel(), 
            pseudoFile
        );
        
        updateTable();
    }
    
    private void updateTable(){
        try {
            controller.updateTable();
        } catch (IOException e) {
            fileExceptionDialog();
        }
    }

    private void fileExceptionDialog(){
        InfoDialog dialog = new InfoDialog(null, "Error", 
            "Un error inesperado acaba de ocurrir", InfoDialog.TypeInfoDialog.ERROR_DIALOG
        );
        dialog.setVisible(true);
    }

    private void pickARowDialog(){
        InfoDialog dialog = new InfoDialog(null, "Ninguna fila selecionada", 
            "Por favor seleciona un registro", 
            InfoDialog.TypeInfoDialog.INFO_DIALOG
        );
        dialog.setVisible(true);
    }
    
    private boolean deleteWarningDialog(){
        WarningDialog dialog = new WarningDialog(null, "Advertencia", 
            "¿Está seguro de eliminar el registro?"
        );
        dialog.setVisible(true);
        return dialog.IsWarningAccepted();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        card_content_layout = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        appo_type_table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        add_button = new javax.swing.JButton();
        modify_button = new javax.swing.JButton();
        delete_product_button = new javax.swing.JButton();

        card_content_layout.setBackground(new java.awt.Color(247, 249, 249));

        appo_type_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "tipo", "nombre", "tiempo", "precioHora", "precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(appo_type_table);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        add_button.setBackground(new java.awt.Color(64, 145, 108));
        add_button.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        add_button.setForeground(new java.awt.Color(255, 255, 255));
        add_button.setText("Añadir TipoCita");
        add_button.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 25, 10, 25));
        add_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAdd(evt);
            }
        });
        jPanel1.add(add_button);

        modify_button.setBackground(new java.awt.Color(64, 145, 108));
        modify_button.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        modify_button.setForeground(new java.awt.Color(255, 255, 255));
        modify_button.setText("Editar TipoCita");
        modify_button.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 25, 10, 25));
        modify_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modify_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onModify(evt);
            }
        });
        jPanel1.add(modify_button);

        delete_product_button.setBackground(new java.awt.Color(64, 145, 108));
        delete_product_button.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        delete_product_button.setForeground(new java.awt.Color(255, 255, 255));
        delete_product_button.setText("Eliminar TipoCita");
        delete_product_button.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 25, 10, 25));
        delete_product_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_product_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDelete(evt);
            }
        });
        jPanel1.add(delete_product_button);

        javax.swing.GroupLayout card_content_layoutLayout = new javax.swing.GroupLayout(card_content_layout);
        card_content_layout.setLayout(card_content_layoutLayout);
        card_content_layoutLayout.setHorizontalGroup(
            card_content_layoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card_content_layoutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(card_content_layoutLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        card_content_layoutLayout.setVerticalGroup(
            card_content_layoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card_content_layoutLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(card_content_layout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(card_content_layout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void onAdd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAdd
        AppoTypeViewForm dialogForm = new AppoTypeViewForm(
                (JFrame) SwingUtilities.getWindowAncestor(this), true
        );
        dialogForm.setBaseController(controller);
        dialogForm.setVisible(true);
    }//GEN-LAST:event_onAdd

    private void onModify(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onModify
        int row = appo_type_table.getSelectedRow();
        if (row != -1){
            AppoTypeViewForm dialogForm = new AppoTypeViewForm(
                (JFrame) SwingUtilities.getWindowAncestor(this), true
            );
            dialogForm.setFields(controller.getDataFromRow(row), row);
            dialogForm.setBaseController(controller);
            dialogForm.setVisible(true);
        }else{
            pickARowDialog();
        }
    }//GEN-LAST:event_onModify

    private void onDelete(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDelete
        int row = appo_type_table.getSelectedRow();
        if (row != -1){
            if(deleteWarningDialog()){
                controller.getTableModel().removeRow(row);
                try {
                    controller.reWriteFile();
                } catch (IOException e) {
                    fileExceptionDialog();
                }
            }
        }else{
            pickARowDialog();
        }
    }//GEN-LAST:event_onDelete


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JTable appo_type_table;
    private javax.swing.JPanel card_content_layout;
    private javax.swing.JButton delete_product_button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modify_button;
    // End of variables declaration//GEN-END:variables
}
