package views.adminviews;

import controllers.BaseController;
import controllers.SimpleController;
import inevaup.dialogs.InfoDialog;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.File;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import models.Appointment;
import pseudofiles.PseudoFile;
import views.vetviews.AppoInfoView;

public class AppoimentView extends javax.swing.JPanel {
    
    private final BaseController controller;
    
    public AppoimentView() {
        initComponents();
        
        PseudoFile pseudoFile = new PseudoFile(
            new File("data/citas.csv"), 
            Appointment.getColumns()
        );

        controller = new SimpleController(
            (DefaultTableModel) appo_table.getModel(), 
            pseudoFile
        );
  
        setListeners();
        
    }
    
    private void pickARowDialog(){
        InfoDialog dialog = new InfoDialog(null, "Ninguna fila selecionada", 
            "Por favor seleciona un registro", 
            InfoDialog.TypeInfoDialog.INFO_DIALOG
        );
        dialog.setVisible(true);
    }
    
    private void setListeners(){
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent evt) {
                 updateTable();
            }
        });
    }
    
    private void updateTable(){
        try {
            controller.updateTable();
        } catch (IOException e) {
            fileExceptionDialog();
        }
    }
    
    private void fileExceptionDialog(){
        InfoDialog dialog = new InfoDialog(null, "Error", 
            "Un error inesperado acaba de ocurrir", InfoDialog.TypeInfoDialog.ERROR_DIALOG
        );
        dialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        card_content_layout = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        appo_table = new javax.swing.JTable();
        add_button4 = new javax.swing.JButton();

        card_content_layout.setBackground(new java.awt.Color(247, 249, 249));

        appo_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idCita", "tipoCita", "empieza", "idMascota", "cedVet"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(appo_table);

        add_button4.setBackground(new java.awt.Color(64, 145, 108));
        add_button4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        add_button4.setForeground(new java.awt.Color(255, 255, 255));
        add_button4.setText("Ver cita");
        add_button4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 25, 10, 25));
        add_button4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_button4OnAppoInfo(evt);
            }
        });

        javax.swing.GroupLayout card_content_layoutLayout = new javax.swing.GroupLayout(card_content_layout);
        card_content_layout.setLayout(card_content_layoutLayout);
        card_content_layoutLayout.setHorizontalGroup(
            card_content_layoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_content_layoutLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(card_content_layoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(card_content_layoutLayout.createSequentialGroup()
                    .addGap(323, 323, 323)
                    .addComponent(add_button4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(324, Short.MAX_VALUE)))
        );
        card_content_layoutLayout.setVerticalGroup(
            card_content_layoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card_content_layoutLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(card_content_layoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(card_content_layoutLayout.createSequentialGroup()
                    .addGap(445, 445, 445)
                    .addComponent(add_button4)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(card_content_layout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(card_content_layout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void add_button4OnAppoInfo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_button4OnAppoInfo
        int row = appo_table.getSelectedRow();
        if (row != -1){
            AppoInfoView appoInfoView = new AppoInfoView(
                (JFrame) SwingUtilities.getWindowAncestor(this), true);
            PseudoFile pseudoFile = new PseudoFile(
                new File("data/citas.csv"),
                Appointment.getColumns()
            );
            try {
                appoInfoView.setAppoInfo(pseudoFile,
                    (String)controller.getTableModel().getValueAt(row, 0)
                );
            } catch (IOException ex) {
                fileExceptionDialog();
            }
            appoInfoView.setVisible(true);
        }else{
            pickARowDialog();
        }
    }//GEN-LAST:event_add_button4OnAppoInfo


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button4;
    private javax.swing.JTable appo_table;
    private javax.swing.JPanel card_content_layout;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
