package authviews;

import adminviews.AdminView;
import clientviews.ClientView;
import clientviews.RegisterViewForm;
import inevaup.dialogs.InfoDialog;
import inevaup.dialogs.InfoDialog.TypeInfoDialog;
import models.Client;
import models.Veterinarian;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import pseudofiles.PseudoFile;
import vetapp.AuthManager;
import vetviews.VetView;

public class GeneralAuthView extends javax.swing.JFrame {

    public GeneralAuthView() {
        initComponents();

        centreWindow();
    }

    private void centreWindow() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y - 25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        header_title = new javax.swing.JLabel();
        content_layout = new javax.swing.JPanel();
        client_form = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        user_label = new javax.swing.JLabel();
        client_ced_field = new javax.swing.JTextField();
        pass_label = new javax.swing.JLabel();
        client_password_field = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        register_button = new javax.swing.JLabel();
        login_client_button = new javax.swing.JButton();
        client_form1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        user_label1 = new javax.swing.JLabel();
        vet_ced_field = new javax.swing.JTextField();
        pass_label1 = new javax.swing.JLabel();
        vet_password_field = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        login_vet_button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        admin_login_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(247, 249, 249));

        header.setBackground(new java.awt.Color(45, 106, 79));
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.setAlignmentY(0.0F);
        header.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 40, 30));

        header_title.setBackground(new java.awt.Color(55, 71, 79));
        header_title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        header_title.setForeground(new java.awt.Color(255, 255, 255));
        header_title.setText("Veterinaria");
        header.add(header_title);

        content_layout.setBackground(new java.awt.Color(247, 249, 249));

        client_form.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(2, 2, 0, 10));

        user_label.setBackground(new java.awt.Color(247, 249, 249));
        user_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        user_label.setForeground(new java.awt.Color(33, 33, 33));
        user_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-user-normal-24.png"))); // NOI18N
        user_label.setText("Usuario:");
        user_label.setIconTextGap(12);
        jPanel4.add(user_label);

        client_ced_field.setBackground(new java.awt.Color(255, 255, 255));
        client_ced_field.setColumns(15);
        client_ced_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        client_ced_field.setForeground(new java.awt.Color(33, 33, 33));
        client_ced_field.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        client_ced_field.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 189, 189)), javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7)));
        client_ced_field.setMargin(new java.awt.Insets(10, 10, 10, 10));
        client_ced_field.setName(""); // NOI18N
        jPanel4.add(client_ced_field);

        pass_label.setBackground(new java.awt.Color(247, 249, 249));
        pass_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pass_label.setForeground(new java.awt.Color(33, 33, 33));
        pass_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-password-24.png"))); // NOI18N
        pass_label.setText("Contraseña:");
        pass_label.setIconTextGap(12);
        jPanel4.add(pass_label);

        client_password_field.setBackground(new java.awt.Color(255, 255, 255));
        client_password_field.setColumns(15);
        client_password_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        client_password_field.setForeground(new java.awt.Color(0, 0, 0));
        client_password_field.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 189, 189)), javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7)));
        jPanel4.add(client_password_field);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Cliente");

        register_button.setBackground(new java.awt.Color(117, 117, 117));
        register_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        register_button.setForeground(new java.awt.Color(51, 51, 51));
        register_button.setText("Registrate");
        register_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onClientRegister(evt);
            }
        });

        login_client_button.setBackground(new java.awt.Color(64, 145, 108));
        login_client_button.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        login_client_button.setForeground(new java.awt.Color(255, 255, 255));
        login_client_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-login-24.png"))); // NOI18N
        login_client_button.setText("Login");
        login_client_button.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 25, 10, 25));
        login_client_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_client_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClientLogin(evt);
            }
        });

        javax.swing.GroupLayout client_formLayout = new javax.swing.GroupLayout(client_form);
        client_form.setLayout(client_formLayout);
        client_formLayout.setHorizontalGroup(
            client_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(client_formLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(client_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, client_formLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, client_formLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(158, 158, 158))))
            .addGroup(client_formLayout.createSequentialGroup()
                .addGroup(client_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(client_formLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(register_button))
                    .addGroup(client_formLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(login_client_button)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        client_formLayout.setVerticalGroup(
            client_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(client_formLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(login_client_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(register_button)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        client_form1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridLayout(2, 2, 0, 10));

        user_label1.setBackground(new java.awt.Color(247, 249, 249));
        user_label1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        user_label1.setForeground(new java.awt.Color(33, 33, 33));
        user_label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-user-normal-24.png"))); // NOI18N
        user_label1.setText("Usuario:");
        user_label1.setIconTextGap(12);
        jPanel5.add(user_label1);

        vet_ced_field.setBackground(new java.awt.Color(255, 255, 255));
        vet_ced_field.setColumns(15);
        vet_ced_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vet_ced_field.setForeground(new java.awt.Color(33, 33, 33));
        vet_ced_field.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        vet_ced_field.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 189, 189)), javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7)));
        vet_ced_field.setMargin(new java.awt.Insets(10, 10, 10, 10));
        vet_ced_field.setName(""); // NOI18N
        jPanel5.add(vet_ced_field);

        pass_label1.setBackground(new java.awt.Color(247, 249, 249));
        pass_label1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pass_label1.setForeground(new java.awt.Color(33, 33, 33));
        pass_label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-password-24.png"))); // NOI18N
        pass_label1.setText("Contraseña:");
        pass_label1.setIconTextGap(12);
        jPanel5.add(pass_label1);

        vet_password_field.setBackground(new java.awt.Color(255, 255, 255));
        vet_password_field.setColumns(15);
        vet_password_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vet_password_field.setForeground(new java.awt.Color(0, 0, 0));
        vet_password_field.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 189, 189)), javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7)));
        jPanel5.add(vet_password_field);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Veterinario");

        login_vet_button.setBackground(new java.awt.Color(64, 145, 108));
        login_vet_button.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        login_vet_button.setForeground(new java.awt.Color(255, 255, 255));
        login_vet_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-login-24.png"))); // NOI18N
        login_vet_button.setText("Login");
        login_vet_button.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 25, 10, 25));
        login_vet_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_vet_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onVetLogin(evt);
            }
        });

        javax.swing.GroupLayout client_form1Layout = new javax.swing.GroupLayout(client_form1);
        client_form1.setLayout(client_form1Layout);
        client_form1Layout.setHorizontalGroup(
            client_form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(client_form1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(client_form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, client_form1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, client_form1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, client_form1Layout.createSequentialGroup()
                        .addComponent(login_vet_button)
                        .addGap(110, 110, 110))))
        );
        client_form1Layout.setVerticalGroup(
            client_form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(client_form1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(login_vet_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        admin_login_button.setBackground(new java.awt.Color(64, 145, 108));
        admin_login_button.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        admin_login_button.setForeground(new java.awt.Color(255, 255, 255));
        admin_login_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-login-24.png"))); // NOI18N
        admin_login_button.setText("Login como administrador");
        admin_login_button.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 25, 10, 25));
        admin_login_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin_login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAdminLogin(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(admin_login_button)
                .addGap(244, 244, 244))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(admin_login_button)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout content_layoutLayout = new javax.swing.GroupLayout(content_layout);
        content_layout.setLayout(content_layoutLayout);
        content_layoutLayout.setHorizontalGroup(
            content_layoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_layoutLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(content_layoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(content_layoutLayout.createSequentialGroup()
                        .addComponent(client_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(client_form1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        content_layoutLayout.setVerticalGroup(
            content_layoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_layoutLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(content_layoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(client_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(client_form1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(content_layout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content_layout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onClientLogin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClientLogin
        PseudoFile pseudoFile = new PseudoFile(
            new File("data/clientes.csv"),
            Client.getColumns()
        );

        boolean isAuthenticated;
        AuthManager auth = AuthManager.getAuth();
        isAuthenticated = auth.authenticate(
            pseudoFile, 
            client_ced_field.getText(), 
            client_password_field.getText()
        );
       
        if (isAuthenticated) {
            ClientView clientView = new ClientView();
            clientView.setVisible(true);
            this.dispose();
        } else {
            InfoDialog infoDialog = new InfoDialog(
                null,
                "Error",
                "Usuario y/o Contraseña incorrectos",
                TypeInfoDialog.ERROR_DIALOG
            );
            infoDialog.setVisible(true);
        }
        

    }//GEN-LAST:event_onClientLogin

    private void onVetLogin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onVetLogin
        PseudoFile pseudoFile = new PseudoFile(
            new File("data/veterinarios.csv"),
            Veterinarian.getColumns()
        );

        boolean isAuthenticated;
        AuthManager auth = AuthManager.getAuth();
        isAuthenticated = auth.authenticate(
            pseudoFile, 
            vet_ced_field.getText(), 
            vet_password_field.getText()
        );
       
        if (isAuthenticated) {
            VetView vetView = new VetView();
            vetView.setVisible(true);
            this.dispose();
        } else {
            InfoDialog infoDialog = new InfoDialog(
                null,
                "Error",
                "Usuario y/o Contraseña incorrectos",
                TypeInfoDialog.ERROR_DIALOG
            );
            infoDialog.setVisible(true);
        }
    }//GEN-LAST:event_onVetLogin

    private void onAdminLogin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAdminLogin
        AdminView adminView = new AdminView();
        adminView.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_onAdminLogin

    private void onClientRegister(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onClientRegister
        RegisterViewForm rg = new RegisterViewForm(this, true);
        rg.setVisible(true);
    }//GEN-LAST:event_onClientRegister

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralAuthView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralAuthView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralAuthView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralAuthView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralAuthView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_login_button;
    private javax.swing.JTextField client_ced_field;
    private javax.swing.JPanel client_form;
    private javax.swing.JPanel client_form1;
    private javax.swing.JPasswordField client_password_field;
    private javax.swing.JPanel content_layout;
    private javax.swing.JPanel header;
    private javax.swing.JLabel header_title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton login_client_button;
    private javax.swing.JButton login_vet_button;
    private javax.swing.JLabel pass_label;
    private javax.swing.JLabel pass_label1;
    private javax.swing.JLabel register_button;
    private javax.swing.JLabel user_label;
    private javax.swing.JLabel user_label1;
    private javax.swing.JTextField vet_ced_field;
    private javax.swing.JPasswordField vet_password_field;
    // End of variables declaration//GEN-END:variables
}
